[versions]
# libraries
junit = "4.13.2"
jupiter = "5.7.1"

# plugins
changelog = "2.2.1"
intelliJPlatform = "2.1.0"
kotlin = "2.1.0"
qodana = "2024.2.3"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
junit5 = { module = "org.junit.jupiter:junit-jupiter", version.ref = "jupiter"}

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }